theme: jekyll-theme-architect
title: Mahdieh Asadpour cv
avatar: https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn-media-1.freecodecamp.org%2Fimages%2F0*ngXgBNNdx6iiWP8q.png&imgrefurl=https%3A%2F%2Fwww.freecodecamp.org%2Fnews%2Fwhy-we-will-always-need-new-programming-languages-3415869ea37e%2F&tbnid=w6SYWNfk6jRnLM&vet=12ahUKEwjYpaybhInrAhUFr6QKHd2TDLQQMygXegUIARCGAg..i&docid=DjgPGMnjQ_yKPM&w=800&h=366&q=programming&ved=2ahUKEwjYpaybhInrAhUFr6QKHd2TDLQQMygXegUIARCGAg
instagram: mim_asadpour
description: (970081900)
